create extension if not exists pgcrypto;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'operation_side') then
    create type public.operation_side as enum ('buy', 'sell');
  end if;

  if not exists (select 1 from pg_type where typname = 'operation_status') then
    create type public.operation_status as enum ('open', 'partial', 'closed', 'canceled');
  end if;

  if not exists (select 1 from pg_type where typname = 'operation_event_type') then
    create type public.operation_event_type as enum ('opened', 'partial', 'closed', 'stopped', 'canceled', 'note');
  end if;
end $$;

alter type public.operation_event_type add value if not exists 'stopped';

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  role text not null default 'operator' check (role in ('admin', 'operator')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.operations (
  id uuid primary key default gen_random_uuid(),
  pair text not null,
  side public.operation_side not null,
  entry_price numeric not null check (entry_price > 0),
  stop_loss numeric not null check (stop_loss > 0),
  take_profit numeric not null check (take_profit > 0),
  point_size numeric not null default 0.0001 check (point_size > 0),
  status public.operation_status not null default 'open',
  stop_points numeric not null default 0,
  take_profit_points numeric not null default 0,
  close_price numeric,
  result_points numeric,
  notes text,
  created_by uuid references auth.users(id) default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  closed_at timestamptz
);

create table if not exists public.operation_events (
  id uuid primary key default gen_random_uuid(),
  operation_id uuid not null references public.operations(id) on delete cascade,
  type public.operation_event_type not null,
  price numeric,
  points numeric,
  close_percent numeric check (close_percent > 0 and close_percent <= 100),
  note text,
  message_text text,
  message_sent boolean not null default false,
  external_message_id text,
  created_by uuid references auth.users(id) default auth.uid(),
  created_at timestamptz not null default now()
);

create table if not exists public.message_queue (
  id uuid primary key default gen_random_uuid(),
  operation_event_id uuid not null references public.operation_events(id) on delete cascade,
  channel text not null default 'trading_group',
  payload jsonb not null,
  status text not null default 'queued' check (status in ('queued', 'sent', 'failed')),
  attempts integer not null default 0,
  last_error text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.operations
  add column if not exists operation_number bigint generated by default as identity;

with seed as (
  select coalesce(max(operation_number), 0) as value
  from public.operations
),
numbered as (
  select
    o.id,
    (select value from seed) + row_number() over (order by o.created_at, o.id) as operation_number
  from public.operations as o
  where o.operation_number is null
)
update public.operations as o
set operation_number = numbered.operation_number
from numbered
where o.id = numbered.id;

do $$
declare
  operation_number_sequence text;
begin
  select pg_get_serial_sequence('public.operations', 'operation_number')
    into operation_number_sequence;

  if operation_number_sequence is not null then
    perform setval(
      operation_number_sequence,
      coalesce((select max(operation_number) from public.operations), 0) + 1,
      false
    );
  end if;
end $$;

create unique index if not exists operations_operation_number_idx
  on public.operations(operation_number)
  where operation_number is not null;

alter table public.operation_events
  add column if not exists close_percent numeric;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'operation_events_close_percent_check'
      and conrelid = 'public.operation_events'::regclass
  ) then
    alter table public.operation_events
      add constraint operation_events_close_percent_check
      check (close_percent is null or (close_percent > 0 and close_percent <= 100));
  end if;
end $$;

create index if not exists operations_status_created_at_idx
  on public.operations(status, created_at desc);

create index if not exists operations_closed_at_idx
  on public.operations(closed_at desc)
  where closed_at is not null;

create index if not exists operation_events_operation_id_created_at_idx
  on public.operation_events(operation_id, created_at desc);

create index if not exists message_queue_status_created_at_idx
  on public.message_queue(status, created_at);

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select role from public.profiles where id = auth.uid()),
    'operator'
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'operator')
  on conflict (id) do update
    set email = excluded.email,
        updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

insert into public.profiles (id, email, role)
select id, email, 'operator'
from auth.users
on conflict (id) do update
  set email = excluded.email,
      updated_at = now();

create or replace function public.set_operation_points()
returns trigger
language plpgsql
as $$
begin
  if new.point_size <= 0 then
    raise exception 'point_size must be greater than zero';
  end if;

  if new.side = 'buy' then
    new.stop_points := round(((new.entry_price - new.stop_loss) / new.point_size)::numeric, 1);
    new.take_profit_points := round(((new.take_profit - new.entry_price) / new.point_size)::numeric, 1);
  else
    new.stop_points := round(((new.stop_loss - new.entry_price) / new.point_size)::numeric, 1);
    new.take_profit_points := round(((new.entry_price - new.take_profit) / new.point_size)::numeric, 1);
  end if;

  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists set_operation_points_trigger on public.operations;
create trigger set_operation_points_trigger
  before insert or update of side, entry_price, stop_loss, take_profit, point_size
  on public.operations
  for each row execute function public.set_operation_points();

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists touch_profiles_updated_at on public.profiles;
create trigger touch_profiles_updated_at
  before update on public.profiles
  for each row execute function public.touch_updated_at();

drop trigger if exists touch_message_queue_updated_at on public.message_queue;
create trigger touch_message_queue_updated_at
  before update on public.message_queue
  for each row execute function public.touch_updated_at();

create or replace function public.apply_operation_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.type::text = 'partial' then
    update public.operations
      set status = 'partial',
          updated_at = now()
      where id = new.operation_id
        and status in ('open', 'partial');
  elsif new.type::text in ('closed', 'stopped') then
    update public.operations
      set status = 'closed',
          close_price = new.price,
          result_points = (
            select coalesce(sum(e.points), 0)
            from public.operation_events as e
            where e.operation_id = new.operation_id
              and e.type::text in ('partial', 'closed', 'stopped')
          ),
          closed_at = coalesce(closed_at, now()),
          updated_at = now()
      where id = new.operation_id;
  elsif new.type::text = 'canceled' then
    update public.operations
      set status = 'canceled',
          closed_at = coalesce(closed_at, now()),
          updated_at = now()
      where id = new.operation_id;
  end if;

  return new;
end;
$$;

drop trigger if exists apply_operation_event_trigger on public.operation_events;
create trigger apply_operation_event_trigger
  after insert on public.operation_events
  for each row execute function public.apply_operation_event();

create or replace function public.enqueue_operation_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  operation_pair text;
  operation_side public.operation_side;
  operation_number bigint;
begin
  if coalesce(new.message_text, '') = '' then
    return new;
  end if;

  select o.pair, o.side, o.operation_number
    into operation_pair, operation_side, operation_number
  from public.operations as o
  where o.id = new.operation_id;

  insert into public.message_queue (operation_event_id, payload)
  values (
    new.id,
    jsonb_build_object(
      'text', new.message_text,
      'operation_id', new.operation_id,
      'event_id', new.id,
      'event_type', new.type,
      'pair', operation_pair,
      'side', operation_side,
      'operation_number', operation_number,
      'price', new.price,
      'points', new.points,
      'close_percent', new.close_percent
    )
  );

  return new;
end;
$$;

drop trigger if exists enqueue_operation_message_trigger on public.operation_events;
create trigger enqueue_operation_message_trigger
  after insert on public.operation_events
  for each row execute function public.enqueue_operation_message();

create or replace view public.monthly_operation_stats as
select
  date_trunc('month', closed_at)::date as month,
  count(*)::integer as closed_operations,
  coalesce(sum(result_points), 0)::numeric as total_points,
  count(*) filter (where result_points > 0)::integer as wins,
  count(*) filter (where result_points < 0)::integer as losses,
  count(*) filter (where result_points = 0)::integer as breakevens,
  coalesce(avg(result_points), 0)::numeric as average_points
from public.operations
where status = 'closed'
  and closed_at is not null
group by 1;

alter table public.profiles enable row level security;
alter table public.operations enable row level security;
alter table public.operation_events enable row level security;
alter table public.message_queue enable row level security;

drop policy if exists "profiles select own or admin" on public.profiles;
create policy "profiles select own or admin"
  on public.profiles for select
  to authenticated
  using (id = auth.uid() or public.current_user_role() = 'admin');

drop policy if exists "profiles admin manage" on public.profiles;
create policy "profiles admin manage"
  on public.profiles for all
  to authenticated
  using (public.current_user_role() = 'admin')
  with check (public.current_user_role() = 'admin');

drop policy if exists "operations authenticated read" on public.operations;
create policy "operations authenticated read"
  on public.operations for select
  to authenticated
  using (true);

drop policy if exists "operations admin manage" on public.operations;
create policy "operations admin manage"
  on public.operations for all
  to authenticated
  using (public.current_user_role() = 'admin')
  with check (public.current_user_role() = 'admin');

drop policy if exists "operation events authenticated read" on public.operation_events;
create policy "operation events authenticated read"
  on public.operation_events for select
  to authenticated
  using (true);

drop policy if exists "operation events admin manage" on public.operation_events;
create policy "operation events admin manage"
  on public.operation_events for all
  to authenticated
  using (public.current_user_role() = 'admin')
  with check (public.current_user_role() = 'admin');

drop policy if exists "message queue admin manage" on public.message_queue;
create policy "message queue admin manage"
  on public.message_queue for all
  to authenticated
  using (public.current_user_role() = 'admin')
  with check (public.current_user_role() = 'admin');

grant usage on schema public to anon, authenticated;
grant select on public.monthly_operation_stats to authenticated;
grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.operations to authenticated;
grant select, insert, update, delete on public.operation_events to authenticated;
grant select, insert, update, delete on public.message_queue to authenticated;
